### ISSUE TITLE
I wanna show something

### ISSUE THREAD

**Issue by davidhsonic** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#2]
@jlmayfield Do you know if there's any way I could share an html file through GitHub where it would show up as an actual page and not the raw code?

**Comment by jlmayfield** [comment]
Maybe... You can host full websites on github using [github pages](https://guides.github.com/features/pages/).  Otherwise, you could potentially trick github by saving the file as markdown not html. Github will display rendered markdown, not raw code, and you should be able to embed html in markdown without a problem.

**Comment by davidhsonic** [comment]
I just tried the latter in the temp branch I made in this repository, and it almost worked, but not completely.

**Comment by jlmayfield** [comment]
I didn't think scripts would work because markdown only covers static HTML elements, i.e. things that are just pure markup with no dynamic display content based on conditions or other code-like logic.
